### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by jeffRao** [Peachypie98/RivaGAN#5]
i got an exception When I followed the readme steps to validate locally.

local environment：
> OS: win 11
> python: 3.11.9
> torch: torch-2.0.1+cpu-cp311-cp311-win_amd64.whl (I am using the CPU version because I do not have a GPU)
> numpy: 1.26.4

exception:
```
Traceback (most recent call last):
  File "F:\workspace\RivaGAN\inference.py", line 743, in <module>
    model = RivaGAN(data_dim=args.data_dim)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\workspace\RivaGAN\inference.py", line 501, in __init__
    self.adversary = Adversary().cuda()
                     ^^^^^^^^^^^^^^^^^^
  File "F:\workspace\RivaGAN\venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\workspace\RivaGAN\venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\workspace\RivaGAN\venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "F:\workspace\RivaGAN\venv\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "F:\workspace\RivaGAN\venv\Lib\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                                 ^^^^^^^^^^^^^^
  File "F:\workspace\RivaGAN\venv\Lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

i have no idea what happened.
Do you know what the reason is? I would greatly appreciate it if you could reply to me .

**Comment by Peachypie98** [comment]
That assertion error you're seeing is due to Pytorch not being installed with GPU support. To address this, is simply replace all `.cuda()` to `.to(device)` in the code, where device is set to CPU if a GPU is not detected.

**Comment by jeffRao** [comment]
> That assertion error you're seeing is due to Pytorch not being installed with GPU support. To address this, is simply replace all `.cuda()` to `.to(device)` in the code, where device is set to CPU if a GPU is not detected.

it really worked. but it takes 300 hours to process a 5min video with CPU.  -_-|||

**Comment by Peachypie98** [comment]
Yes, In general, I don't recommend using CPU when running AI models, especially the heavy ones.

**Comment by Peachypie98** [comment]
Since this issue is resolved, I will close it. Please feel free to reopen it or create a new one if any further issues arise.
